{
    "name": "Requiez Instance",
    "author": "Vauxoo, Humanytek",
    "summary": """
    All the necessary modules to auto install our service instance
    """,
    "website": "https://requiez.com",
    "license": "LGPL-3",
    "category": "requiez",
    "version": "11.0.2.0.0",
    "depends": [
        "stock",
        "purchase",
        "delivery",
        "sale",
        "sale_order_dates",
        "mrp",
        "sale_brand",
        "mass_editing",
        "sale_order_observation",
        "stock_kardex",
        "sale_stock",
        "stock_no_negative",
        "product_supply",
        "stock_lot_validation",
        "sale_commission",
        "product_compromise",
        "mrp_ii",
        "l10n_mx_edi_payment",
        "l10n_mx_edi_landing",
        "l10n_mx_edi_external_trade",
        "l10n_mx_edi_customs",
        "l10n_mx_reports",
        "l10n_mx_edi_vendor_bills",
        "l10n_mx_import_taxes",
        "l10n_mx_check_printing",
        "account_cash_basis_base_account",
        "mrp_mps",
    ],
    "data": [
        "data/chart_template.xml",
        # Security
        "security/ir.model.access.csv",
        "security/responsible_confirm_order_security.xml",
        "security/invoice_prioritize_security.xml",
        "security/archive_product_security.xml",
        # Data
        "data/res_company_data.xml",
        "data/report_data.xml",
        "data/mail_template_data.xml",
        # Views
        "view/res_partner_view.xml",
        "view/product_view.xml",
        "view/res_partner_view.xml",
        "view/product_view.xml",
        "view/purchase_view.xml",
        "view/sale_view.xml",
        "view/account_invoice_view.xml",
        "view/stock_picking_views.xml",
        "view/template.xml",
        "view/stock_location_views.xml",
        "view/mrp_mps_report_view.xml",
        "view/mrp_production_views.xml",
        "wizard/upload_forecast_view.xml",
        # Reports
        "report/requiez_reports_definition.xml",
        "report/mrp_report_template.xml",
        'report/sale_report_template.xml',
        "report/product_label_picking_template.xml",
        "report/shipping_label_template.xml",
        "report/shipping_order_template.xml",
        "report/product_label_mrp_template.xml",
        "report/report_invoice.xml",
        "report/purchase_order_templates.xml",
        "report/purchase_quotation_templates.xml",
        "report/mrp_mps_report_templates.xml",
    ],
    "demo": [
    ],
    "test": [
    ],
    "qweb": [],
    "pre_init_hook": "pre_init_hook",
    "auto_install": False,
    "application": True,
    "installable": True,
}
